# Generated by Django 3.1.6 on 2021-04-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoMoCcino', '0002_carouselimage_category_image_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=20)),
                ('sold_units', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populars', to='RoMoCcino.item')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='RoMoCcino.popular'),
        ),
    ]
