# Generated by Django 3.1.6 on 2021-04-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoMoCcino', '0003_auto_20210409_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='main_display',
            field=models.BooleanField(default=False),
        ),
    ]
