# Generated by Django 3.1.6 on 2021-04-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoMoCcino', '0004_image_main_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoMoCcino.image'),
        ),
    ]
