# Generated by Django 3.1.6 on 2021-04-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RoMoCcino', '0005_auto_20210410_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='RoMoCcino.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(default='google.com'),
        ),
    ]
