# Generated by Django 3.1.6 on 2021-04-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoMoCcino', '0008_auto_20210410_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='RoMoCcino.CartItem'),
        ),
    ]
